name: Build Client

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-windows:
    name: Build Windows (Win32)
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure CMake
        run: cmake -A Win32 -B build -DCMAKE_BUILD_TYPE=Release
        
      - name: Build
        run: cmake --build build --config Release
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fragmount-client-windows
          path: |
            build/csgo_gc/Release/csgo_gc.dll
            build/launcher/Release/cc.exe
            build/launcher/Release/srcds.exe

  build-linux:
    name: Build Linux (x86)
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib
          
      - name: Configure CMake
        run: cmake -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_ASM_FLAGS=-m32 -B build -DCMAKE_BUILD_TYPE=Release
        
      - name: Build
        run: cmake --build build --config Release
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fragmount-client-linux
          path: |
            build/csgo_gc/csgo_gc.so
            build/launcher/cc_linux
            build/launcher/srcds_linux
